### ISSUE TITLE
Docker run hangs without any message or error

### ISSUE THREAD

**Issue by craneabove** [ysf465639310/CLOUD_MEDIASOUP#1]
Hi yangshaofei,

First off, thanks for bundling this together with nginx, makes trying things out simple. I was in the midst of executing the command 

```console
$ docker run ysf465639310/mediasoup-demo-cloud:v2
```

and it hangs with no message or response. Any idea what that could be? 

Running it on 4 GB VPS with 2 vCPUs

**Comment by ysf465639310** [comment]
you should use it with your own command,  I recommend docker-compose  [readme](https://github.com/ysf465639310/CLOUD_MEDIASOUP/blob/master/README.md)

**Comment by ysf465639310** [comment]
I'll update new image and fix it

**Comment by craneabove** [comment]
Okay great, thanks! I also just noticed that the nginx config in the readme is different than the one in the repo. Hopefully that helps.
